# Generated by Django 3.1.1 on 2020-11-23 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(db_index=True, max_length=256)),
                ('lastSeen', models.DateTimeField(auto_now=True)),
                ('inRoom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.room')),
            ],
        ),
    ]
