# Generated by Django 3.1.1 on 2020-12-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='orderPrio',
            field=models.IntegerField(default=0),
        ),
    ]
