# Generated by Django 3.1.1 on 2021-03-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_room_orderprio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external',
            field=models.BooleanField(default=False),
        ),
    ]
